/**
 * T166 — agentsgate report: markdown compliance summary generation.
 * Tests the report logic end-to-end via StateStore + the same aggregation
 * that cmdReport uses, without spawning a subprocess.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs/promises';
import { StateStore } from '../src/modules/m2-store/index.js';
import type { MCPOperation, ProxyDecision } from '../src/types/interfaces.js';

// Duplicate the report aggregation logic so we can unit-test it without
// importing the CLI module (which calls process.exit on bad input).
function generateReport(
  logs: Array<{ operation: MCPOperation; decision: ProxyDecision; createdAt: Date }>,
  generatedAt = new Date().toISOString()
): string {
  const totalOps = logs.length;
  const byAction: Record<string, number> = { allow: 0, block: 0, require_approval: 0 };
  const byTool: Record<string, number> = {};
  const byAgent: Record<string, number> = {};
  let riskSum = 0;
  const riskBuckets: Record<string, number> = {
    '0.0-0.2': 0, '0.2-0.4': 0, '0.4-0.6': 0, '0.6-0.8': 0, '0.8-1.0': 0,
  };

  for (const l of logs) {
    const action = l.decision.action;
    byAction[action] = (byAction[action] ?? 0) + 1;
    byTool[l.operation.tool] = (byTool[l.operation.tool] ?? 0) + 1;
    byAgent[l.operation.agentId] = (byAgent[l.operation.agentId] ?? 0) + 1;
    const rs = l.decision.riskScore;
    riskSum += rs;
    const bucket = rs < 0.2 ? '0.0-0.2' : rs < 0.4 ? '0.2-0.4' : rs < 0.6 ? '0.4-0.6' : rs < 0.8 ? '0.6-0.8' : '0.8-1.0';
    riskBuckets[bucket]++;
  }
  const avgRisk = totalOps > 0 ? riskSum / totalOps : 0;
  const blockRate = totalOps > 0 ? ((byAction.block ?? 0) / totalOps) * 100 : 0;

  const topTools = Object.entries(byTool).sort((a, b) => b[1] - a[1]).slice(0, 10);
  const topAgents = Object.entries(byAgent).sort((a, b) => b[1] - a[1]).slice(0, 10);

  let windowStart = '';
  let windowEnd = '';
  if (logs.length > 0) {
    const times = logs.map(l => new Date(l.createdAt).getTime());
    windowStart = new Date(Math.min(...times)).toISOString();
    windowEnd   = new Date(Math.max(...times)).toISOString();
  }

  const lines: string[] = [
    `# AgentsGate Compliance Report`,
    ``,
    `**Generated:** ${generatedAt}`,
    `**Operation window:** ${windowStart || 'N/A'} — ${windowEnd || 'N/A'}`,
    `**Operations sampled:** ${totalOps}`,
    ``,
    `---`,
    ``,
    `## Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total operations | ${totalOps} |`,
    `| Allowed | ${byAction.allow ?? 0} (${totalOps > 0 ? (((byAction.allow ?? 0) / totalOps) * 100).toFixed(1) : 0}%) |`,
    `| Blocked | ${byAction.block ?? 0} (${blockRate.toFixed(1)}%) |`,
    `| Require approval | ${byAction.require_approval ?? 0} (${totalOps > 0 ? (((byAction.require_approval ?? 0) / totalOps) * 100).toFixed(1) : 0}%) |`,
    `| Average risk score | ${avgRisk.toFixed(3)} |`,
  ];

  const blocked = logs.filter(l => l.decision.action === 'block').slice(0, 20);
  lines.push('');
  lines.push('## Recent Blocked Operations');
  lines.push('');
  if (blocked.length === 0) {
    lines.push('*No blocked operations in this sample.*');
  } else {
    lines.push('| Time | Agent | Tool | Reason |');
    lines.push('|------|-------|------|--------|');
    for (const l of blocked) {
      const t = new Date(l.createdAt).toISOString();
      const reason = l.decision.reasons[0] ?? '';
      lines.push(`| ${t} | ${l.operation.agentId} | ${l.operation.tool} | ${reason} |`);
    }
  }

  lines.push('', '---', '', '*Report generated by AgentsGate CLI.*', '');
  return lines.join('\n');
}

function makeLog(
  tool: string,
  agentId: string,
  action: ProxyDecision['action'],
  riskScore: number,
  reason = 'test reason'
): { operation: MCPOperation; decision: ProxyDecision; createdAt: Date } {
  return {
    operation: { id: 'op-1', agentId, tool, method: 'call', params: {}, timestamp: new Date(), sessionId: 's1' },
    decision: { action, riskScore, reasons: [reason] },
    createdAt: new Date(),
  };
}

describe('agentsgate report — compliance summary generation', () => {
  it('generates a report with correct totals', () => {
    const logs = [
      makeLog('filesystem', 'agent-1', 'allow', 0.1),
      makeLog('shell', 'agent-1', 'block', 0.9, 'Destructive command blocked'),
      makeLog('filesystem', 'agent-2', 'require_approval', 0.5),
    ];
    const report = generateReport(logs, '2026-01-01T00:00:00.000Z');
    expect(report).toContain('**Operations sampled:** 3');
    expect(report).toContain('| Total operations | 3 |');
    expect(report).toContain('| Allowed | 1 (33.3%) |');
    expect(report).toContain('| Blocked | 1 (33.3%) |');
    expect(report).toContain('| Require approval | 1 (33.3%) |');
  });

  it('includes blocked operations table when blocks exist', () => {
    const logs = [
      makeLog('shell', 'agent-1', 'block', 0.9, 'Rate limit exceeded'),
    ];
    const report = generateReport(logs);
    expect(report).toContain('| Time | Agent | Tool | Reason |');
    expect(report).toContain('agent-1');
    expect(report).toContain('shell');
    expect(report).toContain('Rate limit exceeded');
  });

  it('shows "No blocked operations" when none are present', () => {
    const logs = [
      makeLog('filesystem', 'agent-1', 'allow', 0.1),
      makeLog('filesystem', 'agent-2', 'allow', 0.2),
    ];
    const report = generateReport(logs);
    expect(report).toContain('*No blocked operations in this sample.*');
  });

  it('produces N/A window for empty log set', () => {
    const report = generateReport([]);
    expect(report).toContain('**Operation window:** N/A — N/A');
    expect(report).toContain('**Operations sampled:** 0');
  });

  it('computes correct average risk score', () => {
    const logs = [
      makeLog('filesystem', 'agent-1', 'allow', 0.2),
      makeLog('shell', 'agent-1', 'allow', 0.8),
    ];
    const report = generateReport(logs);
    // avg = (0.2 + 0.8) / 2 = 0.500
    expect(report).toContain('| Average risk score | 0.500 |');
  });

  it('report contains markdown heading and footer', () => {
    const report = generateReport([]);
    expect(report).toContain('# AgentsGate Compliance Report');
    expect(report).toContain('*Report generated by AgentsGate CLI.*');
  });

  it('writes report to file when --output is specified', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'as-report-'));
    const outFile = path.join(tmpDir, 'report.md');
    try {
      const logs = [makeLog('filesystem', 'agent-1', 'allow', 0.1)];
      const report = generateReport(logs, '2026-01-01T00:00:00.000Z');
      await fs.writeFile(outFile, report, 'utf-8');
      const contents = await fs.readFile(outFile, 'utf-8');
      expect(contents).toContain('# AgentsGate Compliance Report');
      expect(contents).toContain('**Operations sampled:** 1');
    } finally {
      await fs.rm(tmpDir, { recursive: true, force: true });
    }
  });
});
